---
name: logsearch
director_uuid: <%= `bosh status --uuid` %>

jobs:
- name: elasticsearch_master
  networks:
  - name: default
    static_ips: (( static_ips(0, 20, 21) ))
  instances: 3

- name: elasticsearch_data
  instances: 2

- name: ingestor
  instances: 1

- name: ingestor-bosh-nats
  instances: 1
  properties:
    nats_to_syslog:
      nats:
        user: nats
        password: nats-password
        port: 4222
        machines: [10.254.50.4]

- name: queue
  instances: 1

- name: parser
  instances: 1

- name: kibana
  instances: 1

- name: maintenance
  instances: 1

- name: cluster_monitor
  instances: 1
  properties:
    nats_to_syslog:
      nats:
        user: nats
        password: nats-password
        port: 4222
        machines: [10.254.50.4]

properties:
  elasticsearch:
    discovery:
      minimum_master_nodes: 2
